/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups/$groupId'
import { Route as AuthenticatedGameDayGameDayIdRouteImport } from './routes/_authenticated/game-day/$gameDayId'
import { Route as AuthenticatedGameDayGameDayIdSummaryRouteImport } from './routes/_authenticated/game-day/$gameDayId_.summary'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGameDayGameDayIdRoute =
  AuthenticatedGameDayGameDayIdRouteImport.update({
    id: '/game-day/$gameDayId',
    path: '/game-day/$gameDayId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGameDayGameDayIdSummaryRoute =
  AuthenticatedGameDayGameDayIdSummaryRouteImport.update({
    id: '/game-day/$gameDayId_/summary',
    path: '/game-day/$gameDayId/summary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-day/$gameDayId': typeof AuthenticatedGameDayGameDayIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/game-day/$gameDayId/summary': typeof AuthenticatedGameDayGameDayIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-day/$gameDayId': typeof AuthenticatedGameDayGameDayIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/game-day/$gameDayId/summary': typeof AuthenticatedGameDayGameDayIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/game-day/$gameDayId': typeof AuthenticatedGameDayGameDayIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/game-day/$gameDayId_/summary': typeof AuthenticatedGameDayGameDayIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game-day/$gameDayId'
    | '/groups/$groupId'
    | '/groups/'
    | '/game-day/$gameDayId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game-day/$gameDayId'
    | '/groups/$groupId'
    | '/groups'
    | '/game-day/$gameDayId/summary'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/game-day/$gameDayId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/groups/'
    | '/_authenticated/game-day/$gameDayId_/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/game-day/$gameDayId': {
      id: '/_authenticated/game-day/$gameDayId'
      path: '/game-day/$gameDayId'
      fullPath: '/game-day/$gameDayId'
      preLoaderRoute: typeof AuthenticatedGameDayGameDayIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/game-day/$gameDayId_/summary': {
      id: '/_authenticated/game-day/$gameDayId_/summary'
      path: '/game-day/$gameDayId/summary'
      fullPath: '/game-day/$gameDayId/summary'
      preLoaderRoute: typeof AuthenticatedGameDayGameDayIdSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedGameDayGameDayIdRoute: typeof AuthenticatedGameDayGameDayIdRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedGameDayGameDayIdSummaryRoute: typeof AuthenticatedGameDayGameDayIdSummaryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGameDayGameDayIdRoute: AuthenticatedGameDayGameDayIdRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedGameDayGameDayIdSummaryRoute:
    AuthenticatedGameDayGameDayIdSummaryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
